FROM node:25-alpine AS web-build
WORKDIR /web
COPY web/package*.json ./
RUN npm install
COPY web/ .
RUN npm run build

FROM golang:1.25 AS go-build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o controller ./cmd/controller \
    && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o agent-amd64 ./cmd/agent \
    && CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o agent-arm64 ./cmd/agent

FROM debian:stable-slim
RUN apt-get update && apt-get install -y \
    ca-certificates \
    mtools \
    wget \
    xz-utils \
    qemu-user-static \
    fdisk \
    mount \
    parted \
    udev \
    e2fsprogs \
    dosfstools \
    && rm -rf /var/lib/apt/lists/*
COPY --from=go-build /app/controller /app/controller
COPY --from=go-build /app/agent-amd64 /app/agent-amd64
COPY --from=go-build /app/agent-arm64 /app/agent-arm64
COPY --from=web-build /web/dist /app/web/dist
ENV WEB_ROOT=/app/web/dist
ENV AGENT_BINARY_DIR=/app
ENV AGENT_BINARY_PATH=/app/agent
EXPOSE 8080
CMD ["/app/controller"]
