FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -ldflags="-s -w" -trimpath -o agent ./cmd/agent

FROM alpine:latest
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=build /app/agent /app/agent
CMD ["/app/agent"]
