services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: turtlebot-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:Z

  traefik:
    image: traefik:v2.11
    container_name: turtlebot-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik Dashboard
    volumes:
      # Map the podman socket to where Traefik expects the docker socket
      - ${PODMAN_SOCKET:-/run/podman/podman.sock}:/var/run/docker.sock:ro
      - traefik-certificates:/letsencrypt:Z
    security_opt:
      - label=disable

  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: turtlebot-controller
    privileged: true
    depends_on:
      - mqtt
    environment:
      - MQTT_BROKER=tcp://mqtt:1883
      - AGENT_MQTT_BROKER=${AGENT_MQTT_BROKER:-tcp://192.168.100.122:1883}
      - DB_PATH=/data/controller.db
      - DEMO_MODE=true
      - SCAN_SUBNETS=192.168.1.0/24,192.168.100.0/24
    volumes:
      - controller-data:/data:Z
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller.rule=PathPrefix(`/`)"
      - "traefik.http.routers.controller.entrypoints=web"
      - "traefik.http.services.controller.loadbalancer.server.port=8080"

volumes:
  controller-data:
  traefik-certificates:
